# @format

name: om_chauhan
description: A Flutter Developer Portfolio Website.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.16.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.1.0
  flutter_svg: ^2.0.4
  url_strategy: ^0.2.0
  url_launcher: ^6.1.0
  firebase_core: ^2.3.0
  cached_network_image: ^3.2.3
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
